version: "3"

networks:
  storage: {}
  processing: {}
  credentials: {}

services:

  api_gateway:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - credentials

  credentials:
    image: ghcr.io/nplettenberg/dataflow_credentials:v0.0.3
    restart: unless-stopped
    environment:
      - MONGO_HOST=${CREDENTIALS_MONGO_HOST}
      - MONGO_PORT=${CREDENTIALS_MONGO_PORT}
      - MONGO_USERNAME=${CREDENTIALS_MONGO_USER}
      - MONGO_PASSWORD=${CREDENTIALS_MONGO_PASSWORD}
      - GIN_MODE=release
    networks:
      - credentials
      - processing

  mongo:
    image: ${MONGO_IMAGE}
    restart: unless-stopped
    ports: 
      - "27017:27017"
    volumes:
      - ${MONGO_DATA_DIRECTORY}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - credentials
  
  minio:
    image: ${MINIO_IMAGE}
    command: server --console-address ":9090" /data
    restart: unless-stopped
    ports:
      - "${MINIO_CONSOLE_PORT}:9000" # Console
      - "${MINIO_API_PORT}:9090" # API
    volumes:
      - ${MINIO_DATA_DIRECTORY}:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - storage

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - processing
