version: "3"

networks:
  storage: {}
  processing: {}
  credentials: {}

services:

  api_gateway:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - credentials
    ports:
      - "8002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - credentials

  credentials:
    image: ghcr.io/nplettenberg/dataflow_credentials:v0.0.5
    restart: unless-stopped
    depends_on:
      - minio
    environment:
      - MINIO_ENDPOINT=${CREDENTIALS_MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${CREDENTIALS_ACCESS_KEY}
      - MINIO_ACCESS_SECRET=${CREDENTIALS_ACCESS_SECRET}
      - GIN_MODE=release
    networks:
      - credentials
      - processing
  
  minio:
    image: ${MINIO_IMAGE}
    command: server --console-address ":9090" /data
    restart: unless-stopped
    ports:
      - "${MINIO_CONSOLE_PORT}:9000" # Console
      - "${MINIO_API_PORT}:9090" # API
    volumes:
      - ${MINIO_DATA_DIRECTORY}:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - storage
      - credentials

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - processing
