version: "3"

networks:
  storage: {}
  processing: {}

services:
  
  minio:
    image: ${MINIO_IMAGE}
    command: server --console-address ":9090" /data
    restart: unless-stopped
    ports:
      - "${MINIO_CONSOLE_PORT}:9000" # Console
      - "${MINIO_API_PORT}:9090" # API
    volumes:
      - ${MINIO_DATA_DIRECTORY}:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - storage

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - processing
